# -*- coding: utf-8 -*-
"""carebot.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11IPsxTKG7-pGmyZ6l1qSPr7T4Hk-NjEj
"""

!pip install datasets scikit-learn

import pandas as pd
from datasets import load_dataset
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity
import random

# --- 1. Load dataset Mental_Health_FAQ dari HuggingFace ---
try:
    df = pd.read_csv("hf://datasets/tolu07/Mental_Health_FAQ/Mental_Health_FAQ.csv")
    # Periksa apakah kolom yang dibutuhkan ada
    if 'Questions' not in df.columns or 'Answers' not in df.columns:
        raise ValueError("Dataset must contain 'Questions' and 'Answers' columns.")
    print("Dataset loaded successfully.")
except Exception as e:
    print(f"Error loading dataset: {e}")
    print("Falling back to dummy data for demonstration.")
    # Fallback to dummy data if loading fails
    data = {
        'Questions': [
            "What is anxiety?", "How to deal with stress?", "Symptoms of depression",
            "I feel tired all the time", "How to relax?", "What is mental health?",
            "Tips for better sleep", "How to manage anger?", "Signs of burnout",
            "I feel overwhelmed", "Ways to cope with sadness", "What is therapy?"
        ],
        'Answers': [
            "Anxiety is a feeling of worry, nervousness, or unease, typically about an event or something with an uncertain outcome.",
            "Managing stress involves techniques like mindfulness, exercise, and setting realistic goals. Try taking breaks.",
            "Symptoms of depression can include persistent sadness, loss of interest, changes in appetite or sleep, and feelings of worthlessness.",
            "Feeling tired can be a sign of many things, from lack of sleep to stress. Ensure you're getting enough rest and managing your energy.",
            "Relaxation techniques include deep breathing exercises, meditation, yoga, or listening to calming music.",
            "Mental health refers to our emotional, psychological, and social well-being. It affects how we think, feel, and act.",
            "For better sleep, establish a regular sleep schedule, create a relaxing bedtime routine, and avoid caffeine before bed.",
            "To manage anger, try deep breathing, taking a timeout, or expressing your feelings assertively but calmly.",
            "Signs of burnout include chronic fatigue, cynicism, and reduced professional efficacy. Take time for self-care.",
            "Feeling overwhelmed is common. Break down tasks into smaller steps, prioritize, and don't hesitate to ask for help.",
            "Coping with sadness can involve allowing yourself to feel emotions, talking to someone, engaging in hobbies, or seeking professional help.",
            "Therapy is a way to treat mental health issues by talking to a trained professional, helping you understand and cope with your thoughts and feelings."
        ]
    }
    df = pd.DataFrame(data)

# --- 2. TF-IDF Vectorization ---
vectorizer = TfidfVectorizer()
faq_vectors = vectorizer.fit_transform(df['Questions'])

# --- 3. Chatbot FAQ Response ---
def chatbot_response(user_input):
    user_vector = vectorizer.transform([user_input])
    similarities = cosine_similarity(user_vector, faq_vectors)
    idx = similarities.argmax()

    # Adjusted threshold for 'no match'. You might need to fine-tune this.
    # A lower threshold makes it more likely to find a match, but might return less relevant answers.
    if similarities[0, idx] < 0.2: # Lowered from 0.4 for potentially better matching
        return "I'm not sure I understand your question. Could you rephrase it or ask about a general mental health topic? Please use English."

    return df.iloc[idx]['Answers']

# --- 4. Stress Level Classification ---
def classify_stress_level(user_input):
    input_lower = user_input.lower()

    # Keywords yang diperbarui
    keywords = {
        "low": [
            "slightly stressed", "a bit worried", "uneasy", "restless", "on edge", "nervous",
            "a little anxious", "mildly pressured", "irritable", "impatient", "fretful",
            "apprehensive", "concerned", "on tenterhooks", "a little bothered", "disquieted",
            "edgy", "uptight", "jittery", "slightly agitated",
            "feel tired", "a bit tired", "sleepy", "feeling drained a little", "just tired",
            "slight headache", "minor ache", "feeling off", "a bit overwhelmed",
            "light pressure", "some pressure", "distracted a bit", "not quite focused",
            "mildly frustrated", "a little annoyed", "slightly irritable", "feeling a bit down",
            "can't focus much", "a bit unfocused", "okay", "fine", "good", "alright", "normal"
        ],
        "optimum": [
            "moderately stressed", "somewhat anxious", "frustrated", "drained", "easily distracted",
            "difficulty concentrating slightly", "feeling the pressure", "a bit overwhelmed", "moody",
            "agitated", "restless", "impatient", "on edge", "tense", "worried",
            "preoccupied", "a little down", "unsettled", "querulous", "irritable",
            "busy day", "heavy workload", "tight deadline", "under pressure", "challenging",
            "feeling responsible", "has responsibilities", "need to finish", "pushing myself",
            "feeling the grind", "productive stress", "focused on tasks", "energized",
            "motivated", "alert", "aware", "sharp", "responsive", "productive", "motivated"
        ],
        "moderate": [
            "stressed", "anxious", "worried", "overwhelmed", "tired", "drained", "frustrated",
            "irritable", "nervous", "restless", "difficulty concentrating", "sleep disturbances",
            "feeling tense", "on edge", "agitated", "preoccupied", "down", "discouraged",
            "impatient", "easily upset", "on a short fuse", "trouble relaxing", "mentally fatigued",
            "emotionally drained",
            "exhausted", "constantly tired", "burnout", "can't cope", "heavy burden",
            "significant pressure", "feeling stuck", "lost interest", "lack of motivation",
            "feeling withdrawn", "avoiding people", "trouble sleeping", "insomnia",
            "headaches often", "stomach issues", "muscle tension", "frequent mood swings",
            "stressed out", "quite anxious", "struggling"
        ],
        "high": [
            "very stressed", "highly anxious", "panicked", "overwhelmed", "unable to cope",
            "severe difficulty concentrating", "significant sleep problems", "intensely frustrated",
            "extremely irritable", "constantly agitated", "feeling trapped", "loss of motivation",
            "helpless", "desperate", "on the verge of breakdown", "consumed by worry",
            "unable to think clearly", "severe mood swings", "social withdrawal", "increased heart rate",
            "muscle tension", "headaches",
            "panic attack", "constant fear", "racing thoughts", "can't stop worrying",
            "feeling of dread", "overthinking", "shaking", "shortness of breath",
            "chest tightness", "dizzy", "nauseous", "trembling", "sweating", "restless nights",
            "nightmares", "avoiding everything", "crying spells", "really bad", "terrible", "miserable"
        ],
        "very high": [
            "severely stressed", "debilitating anxiety", "panic attacks", "completely overwhelmed",
            "hopeless", "helpless", "suicidal thoughts", "worthless", "unable to function",
            "crushed", "paralyzed by stress", "intense emotional pain", "constant state of fear",
            "disconnection from reality", "inability to perform daily tasks", "extreme fatigue",
            "loss of appetite or overeating", "isolation", "feeling like dying", "persistent sadness",
            "self-harm thoughts", "can't get out of bed", "complete shutdown", "no hope",
            "life isn't worth it", "nothing matters", "empty inside", "feeling numb",
            "terrified", "hyperventilating", "loss of control", "screaming inside", "want to die",
            "end it all", "give up", "can't go on"
        ]
    }
    for level, words in keywords.items():
        if any(word in input_lower for word in words):
            return level
    return random.choice(["moderate", "optimum"]) # Default fallback remains

# --- 5. Run Chatbot with Two-Way Interaction ---
print("--- Mental Health Chatbot 🤖 ---")
print("Hello! I'm here to listen and try to help you.")
print("You can tell me how you feel or ask about mental health topics.")
print("Type 'exit' or 'quit' to end the conversation.")
print("----------------------------------")

# Get user's name at the start
user_name = input("Bot: First, what should I call you? ")
if not user_name.strip(): # If user just presses enter or types spaces
    user_name = "User" # Fallback to default name

print(f"Bot: Nice to meet you, {user_name.capitalize()}! Let's begin.")


last_bot_prompt = "" # Stores the last prompt from the bot for context

while True:
    user_input = input(f"{user_name.capitalize()}: ") # Use capitalized name for prompt
    input_lower = user_input.lower().strip()

    if input_lower in ['exit', 'quit']:
        print(f"Bot: Thank you for sharing, {user_name.capitalize()}. Remember, you are not alone. Take care 💙.")
        break

    # --- Simple Context Handling for Bot's Follow-up Questions ---
    if last_bot_prompt: # If the bot previously asked a follow-up question
        if "yes" in input_lower or "yeah" in input_lower or "yup" in input_lower:
            if "additional resources" in last_bot_prompt:
                print("Bot: Certainly. Your campus might have student counseling services. You can also look for professional psychologists or try meditation apps like Calm or Headspace. Do you want more specific details about any type of resource?")
            elif "other tips" in last_bot_prompt:
                print("Bot: Great! Some general tips for maintaining mental health include: getting enough sleep (7-9 hours), regular exercise, eating nutritious food, limiting screen time, and making time for hobbies. Which one interests you most?")
            elif "explore your feelings further" in last_bot_prompt:
                print("Bot: Please tell me more about what's making you feel that way. Sometimes, just talking about it can bring some relief.")
            elif "more specific details" in last_bot_prompt: # Follow-up from 'additional resources'
                print("Bot: Campus counseling offers direct and often free support. Professional psychologists provide more in-depth therapy. Apps can give you tools for meditation or mood tracking. What do you need most right now?")
            elif "interests you most" in last_bot_prompt: # Follow-up from 'other tips'
                print("Bot: I'm ready to provide more information about that!")
            else:
                print("Bot: Okay, let's continue.")
            last_bot_prompt = "" # Reset prompt after handling
            continue # Skip to next input without FAQ/stress detection
        elif "no" in input_lower or "nope" in input_lower:
            print("Bot: Okay, no problem. Is there anything else I can help you with or another topic you'd like to discuss?")
            last_bot_prompt = "" # Reset
            continue # Skip to next input
        elif "what's your name" in input_lower:
            print("Bot: I'm a chatbot designed to support your mental health. You can call me your Mental Assistant.")
            last_bot_prompt = ""
            continue
        elif "how are you" in input_lower:
            print("Bot: I don't have feelings like humans, but I'm here and ready to help you! Thanks for asking.")
            last_bot_prompt = ""
            continue

    # --- Main Process: FAQ and Stress Detection ---
    faq_answer = chatbot_response(user_input)
    stress_level = classify_stress_level(user_input)

    # --- Output Response ---
    print(f"Bot (Personal Response): {faq_answer}")
    print(f"Bot (Detected Stress Level): {stress_level.capitalize()}")

    # --- Follow-up Questions from Bot ---
    if stress_level in ["high", "very high"]:
        last_bot_prompt = f"I understand you're feeling {stress_level} right now, {user_name.capitalize()}. Remember, seeking professional help is a strong act, not a weakness. Would you like to know about additional resources for this situation?"
    elif stress_level == "moderate":
        last_bot_prompt = f"Thanks for sharing, {user_name.capitalize()}. Feeling {stress_level} is common. Remember, it's important to take care of yourself. Is there anything specific you'd like to explore further about your feelings?"
    elif stress_level in ["low", "optimum"]:
        last_bot_prompt = f"Glad to hear you're feeling {stress_level}, {user_name.capitalize()}! Keep up the great work on your mental well-being. Would you like to know any other tips to stay on this positive track?"
    else: # Fallback prompt if stress level is not detected or default
        last_bot_prompt = f"Is there anything else you'd like to talk about or ask, {user_name.capitalize()}?"

    print(f"Bot: {last_bot_prompt}")

